# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e064b30817ece8ed86bd484b3fa7a68b7e5b070094804afa882130c25bfc34e73425a006992eea26f0a5f1f3d5879a9055dab7e18d3fddb24bd035606d91c894

test:
  secret_key_base: d697c3b46da9d7264905e30d8660639d0715206f41183de3ddd3ac51caac99aa49f484ba9b82eab0ac80a6f10a70b11f1a0f444642af394a7b3e39de344f9472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
