# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!({email: "galbreathcody@gmail.com", username: "admin", password: "password", password_confirmation: "password", admin: true, first_name: "Cody", last_name: "Galbreath", phone: "806-290-7304", :confirmed_at => DateTime.now })
User.create!({email: "jnewsom@fortworthkids.org", username: "jnewsom", password: "password", password_confirmation: "password", admin: true, first_name: "James", last_name: "Newsom", phone: "682-402-6849", :confirmed_at => DateTime.now })


IncidentType.create(name: 'Injury')
IncidentType.create(name: 'Theft')
IncidentType.create(name: 'Vehicle Accident')
IncidentType.create(name: 'Property Damage')
IncidentType.create(name: 'Behavioural')
IncidentType.create(name: 'Abuse')

InvolvedType.create(name: 'Member')
InvolvedType.create(name: 'Staff')
InvolvedType.create(name: 'Guest')
InvolvedType.create(name: 'Other')

SeverityLevel.create(name: 'Negligible')
SeverityLevel.create(name: 'Marginal')
SeverityLevel.create(name: 'Serious')
SeverityLevel.create(name: 'Critical')

Location.create(name: 'OnSite')
Location.create(name: 'OffSite')

Program.create(name: 'Branches')
Program.create(name: "Comin' Up")
Program.create(name: 'ETS')
Program.create(name: 'UB')
Program.create(name: 'Prevention')

Facility.create(name: 'North Fort Worth', address: '2000 Ellis Ave.')
Facility.create(name: 'Butler', address: '1250 I.M. Terrell Cr. N.')
Facility.create(name: 'Panther', address: '1500 Hemphill')
Facility.create(name: 'Administration', address: '3218 E. Belknap')
Facility.create(name: "Comin' Up", address: '3312 E. Belknap Street')
Facility.create(name: 'Nicholas & Louella Martin', address: '3123 Avenue G.')
Facility.create(name: 'J.A. Cavile', address: '5021 Avenue G.')
Facility.create(name: 'Eastside', address: '4651 Ramey Ave.')
Facility.create(name: 'Morningside 10', address: '2751 Mississippi Avenue')
Facility.create(name: 'Uplift Mighty', address: '3700 Mighty Mite Drive')

Area.create(name: 'Gym')
Area.create(name: "Cafeteria")
Area.create(name: 'Teen Room')
Area.create(name: 'Education Room')
Area.create(name: 'RestRoom')
Area.create(name: 'Office')

VehicleOwnership.create(name: 'Boys & Girls Club Owned')
VehicleOwnership.create(name: "Owned by 3rd party")
VehicleOwnership.create(name: 'Chartered')
VehicleOwnership.create(name: 'Lease/Rental')

Bus.create(BUS_NUM: 'BUS #1', PLATE: 'U17-007', FOUR_VIN: '7736')
Bus.create(BUS_NUM: 'BUS #2', PLATE: 'U18-572', FOUR_VIN: '4547')
Bus.create(BUS_NUM: 'BUS #3', PLATE: 'U26-741', FOUR_VIN: '6548')
Bus.create(BUS_NUM: 'BUS #4', PLATE: 'U14-833', FOUR_VIN: '2625')
Bus.create(BUS_NUM: 'BUS #5', PLATE: 'U07-554', FOUR_VIN: '8751')
Bus.create(BUS_NUM: 'BUS #6', PLATE: 'U08-914', FOUR_VIN: '0725')
Bus.create(BUS_NUM: 'BUS #8', PLATE: 'U12-072', FOUR_VIN: '8825')
Bus.create(BUS_NUM: 'BUS #9', PLATE: 'U08-916', FOUR_VIN: '1713')
Bus.create(BUS_NUM: 'BUS #10', PLATE: 'U08-956', FOUR_VIN: '0396')
Bus.create(BUS_NUM: 'BUS #12', PLATE: 'U22-689', FOUR_VIN: '1291')
Bus.create(BUS_NUM: 'BUS #13', PLATE: 'U17-031', FOUR_VIN: '7735')
Bus.create(BUS_NUM: 'BUS #14', PLATE: 'U29-076', FOUR_VIN: '4548')
Bus.create(BUS_NUM: 'BUS #15', PLATE: 'U20-601', FOUR_VIN: '8047')
Bus.create(BUS_NUM: 'BUS #16', PLATE: 'U20-614', FOUR_VIN: '3156')
Bus.create(BUS_NUM: 'BUS #17', PLATE: 'U20-615', FOUR_VIN: '1290')
Bus.create(BUS_NUM: 'BUS #18', PLATE: 'U09-058', FOUR_VIN: '8824')
Bus.create(BUS_NUM: 'BUS #19', PLATE: 'U08-884', FOUR_VIN: '5513')
Bus.create(BUS_NUM: 'BUS #20', PLATE: 'U16-782', FOUR_VIN: '1712')
Bus.create(BUS_NUM: 'BUS #21', PLATE: 'U18-600', FOUR_VIN: '0126')
Bus.create(BUS_NUM: 'BUS #22', PLATE: 'U29-095', FOUR_VIN: '8749')
Bus.create(BUS_NUM: 'BUS #23', PLATE: 'U08-656', FOUR_VIN: '3025')
Bus.create(BUS_NUM: 'BUS #24', PLATE: 'U13-535', FOUR_VIN: '0746')
Bus.create(BUS_NUM: 'BUS #25', PLATE: 'U15-628', FOUR_VIN: '4978')
Bus.create(BUS_NUM: 'BUS #27', PLATE: 'U25-475', FOUR_VIN: '0338')
Bus.create(BUS_NUM: 'BUS #28', PLATE: 'U25-468', FOUR_VIN: '0855')
Bus.create(BUS_NUM: 'BUS #29', PLATE: 'U25-469', FOUR_VIN: '9330')
Bus.create(BUS_NUM: 'Truck', PLATE: 'BF58625', FOUR_VIN: '0442')